name: ""

services:
  python-api:
    build: app/
    container_name: python-api
    ports:
      - "8000:80"
    networks:
      - mongodb-net
    volumes:
      - ./app/main.py:/opt/python-api/main.py
      - ./app/client.py:/opt/python-api/client.py
      - ./app/requirements.txt:/opt/python-api/requirements.txt
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017


  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    networks:
      - mongodb-net
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

networks:
  mongodb-net:
    name: mongodb-net

volumes:
  mongodb_data:
